In [2]:
import numpy as np
from sklearn import preprocessing

In [3]:
input_data = np.array([[5.1, -2.9, 3.3],
                       [-1.2, 7.8, -6.1],
                       [3.9, 0.4, 2.1],
                       [7.3, -9.9, -4.5]])

In [8]:
#Binarize data (binarisasi Data --> mengubah menjadi 0 dan 1)
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("\nBinarized data:\n", data_binarized)


Binarized data:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [7]:
# print mean and standard deviation ( cetak rata-rata dan struktur devisiasi)
print("\nBEFORE:")
print("Mean =", input_data.mean(axis=0))
print("std deviation =", input_data.std(axis=0))


BEFORE:
Mean = [ 3.775 -1.15  -1.3  ]
std deviation = [3.12039661 6.36651396 4.0620192 ]


In [11]:
#Menghapus Rata-rata
data_scaled = preprocessing.scale(input_data)
print("\nAFTER:")
print("Mean =", data_scaled.mean(axis=0))
print("std deviation =", data_scaled.std(axis=0))


AFTER:
Mean = [1.11022302e-16 0.00000000e+00 2.77555756e-17]
std deviation = [1. 1. 1.]


In [13]:
# Min Max scaling ( menentukan Nilai Max dan Min)
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("nMin Max scaled data:\n", data_scaled_minmax)

nMin Max scaled data:
 [[0.74117647 0.39548023 1.        ]
 [0.         1.         0.        ]
 [0.6        0.5819209  0.87234043]
 [1.         0.         0.17021277]]
